//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Корзина
    {
        public int Код_корзины { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public Nullable<int> Код_товара { get; set; }
        public Nullable<int> Количество { get; set; }
        public string Фото { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
