//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователь()
        {
            this.История = new HashSet<История>();
        }
    
        public int Код_пользователя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> Код_паспорта { get; set; }
        public Nullable<int> Код_подразделения { get; set; }
        public Nullable<int> Код_должности { get; set; }
        public string Фото { get; set; }
        public string Телефон { get; set; }
        public string Почта { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<bool> Статус { get; set; }
    
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История> История { get; set; }
        public virtual Паспорт Паспорт { get; set; }
        public virtual Подразделение Подразделение { get; set; }
    }
}
